# Generated by Django 5.1.3 on 2024-11-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_historylog_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hash_field',
            field=models.CharField(blank=True, max_length=32, verbose_name='hash field'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='hash_field',
            field=models.CharField(blank=True, max_length=32, verbose_name='hash field'),
        ),
        migrations.AddField(
            model_name='category',
            name='hash_field',
            field=models.CharField(blank=True, max_length=32, verbose_name='hash field'),
        ),
    ]
