# Generated by Django 5.1.3 on 2024-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_hash_field_bloguser_hash_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='is published'),
        ),
    ]
