# Generated by Django 5.0 on 2024-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_stats_blogpost_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='visited_sessions',
            field=models.JSONField(default=dict, verbose_name='visited sessions'),
        ),
        migrations.AddField(
            model_name='stats',
            name='voted_sessions',
            field=models.JSONField(default=dict, verbose_name='voted sessions'),
        ),
    ]
