# Generated by Django 5.0 on 2024-11-24 15:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_stats_visited_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='visited',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='voted',
        ),
        migrations.AddField(
            model_name='stats',
            name='visited_sessions',
            field=models.JSONField(default=blog.models.Stats.default_dict, verbose_name='visited sessions'),
        ),
        migrations.AddField(
            model_name='stats',
            name='voted_sessions',
            field=models.JSONField(default=blog.models.Stats.default_dict, verbose_name='voted sessions'),
        ),
    ]
