# Generated by Django 5.0 on 2024-11-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_stats_visited_remove_stats_voted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='visited_sessions',
            new_name='visited',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='voted_sessions',
            new_name='voted',
        ),
    ]
