# Generated by Django 5.2.7 on 2026-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_visited_sessions_stats_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='subtitle'),
        ),
    ]
